name: "Hello World"
description: "Greet someone and record the time"
inputs:
  name:
    description: "Who to greet"
    required: true
    default: "world"

outputs:
  time:
    description: "The time we greeted you"

runs:
  using: "node20"
  main: "dist/index.js"
